[workspace]
members = [
    "pang", "pang_derive",
]
resolver = "2"

[workspace.package]
version = "0.1.5"
license = "MIT OR Apache-2.0"
repository = "https://github.com/qrzbing/pang/"
readme = "./README.md"

[workspace.dependencies]
pang = { path = "pang", version = "0.1.5" }

env_logger = "0.11.8"
libafl_bolts = "0.15.3"
log = "0.4.28"
serde = "1.0.219"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
debug = true
